name: Run Flask App and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_flask_app:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala as dependências
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Run Flask app in background
      run: |
        export FLASK_APP=app2.py
        nohup flask run --host=0.0.0.0 --port=5000 &  
        sleep 30  # Dá mais tempo para garantir que o servidor está rodando

    - name: Test Flask app (using curl)
      run: |
        curl -v http://127.0.0.1:5000/ || (echo "Flask failed to start" && exit 1)

    - name: Run Tests
      run: pytest || echo "Nenhum teste encontrado"

    - name: Stop Flask app
      run: |
        pkill -f flask || echo "Flask já foi encerrado"

