name: Run Flask App and Access HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_flask_app:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala as dependências do requirements.txt
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Run Flask app in background
      run: |
        # Rodar o Flask em segundo plano
        python app2.py &  
        sleep 20  # Espera 20 segundos para garantir que o Flask esteja rodando

    - name: Access Flask page (using curl)
      run: |
        curl http://127.0.0.1:5000/  # Acessa a página inicial

    - name: Run Tests (optional, e.g., Selenium or other)
      run: |
        pytest  # Ou qualquer outro comando de teste que você tenha configurado

    - name: Stop Flask app
      run: |
        pkill python  # Mata o processo Flask após os testes

