name: Run Flask App and Access HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_flask_app:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Ensure upload directory exists
      run: mkdir -p uploads

    - name: Create empty database (if not exists)
      run: touch sistema_protocolo.db

    - name: Run Flask app in background
      run: |
        export FLASK_APP=app2.py
        nohup flask run --host=0.0.0.0 --port=5000 &> flask.log &
        sleep 5
        echo "Verificando logs do Flask:"
        tail -n 20 flask.log

    - name: Wait for Flask to start
      run: |
        for i in {1..30}; do
          if curl --silent --fail http://127.0.0.1:5000/; then
            echo "Flask está rodando!"
            exit 0
          fi
          echo "Aguardando Flask iniciar..."
          sleep 1
        done
        echo "Falha ao iniciar o Flask"
        exit 1

    - name: Access Flask page (using curl)
      run: curl http://127.0.0.1:5000/

    - name: Show Flask logs (in case of failure)
      if: failure()
      run: cat flask.log

    - name: Run Tests (optional)
      run: pytest || echo "Nenhum teste encontrado"

    - name: Stop Flask app
      run: pkill -f flask || echo "Nenhum processo Flask encontrado"


