name: Run Flask App and Access HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_flask_app:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Ensure upload directory exists
      run: mkdir -p uploads  # Garante que o diretório de uploads existe

    - name: Run Flask app in background
      run: |
        python app2.py &> flask.log &  # Salva logs do Flask
        for i in {1..30}; do
          curl --silent --fail http://127.0.0.1:5000/ && break
          echo "Aguardando o Flask iniciar..."
          sleep 1
        done

    - name: Access Flask page (using curl)
      run: curl http://127.0.0.1:5000/

    - name: Show Flask logs (in case of failure)
      if: failure()
      run: cat flask.log  # Mostra os logs do Flask se falhar

    - name: Run Tests (optional)
      run: pytest

    - name: Stop Flask app
      run: pkill -f app2.py  # Mata apenas o processo do Flask
